export const DATE_FORMATS  = [
    'MM/DD/YYYY',
    'MM/DD/YY',
    'M/D/YYYY',
    'M/D/YY',
    'DD/MM/YYYY',
    'DD/MM/YY',
    'D/M/YYYY',
    'D/M/YY',
    'Do MMMM YYYY',
    'Do MMMM YY',
    'Do MMM YYYY',
    'Do MMM YY',
    'YYYY-MM-DD',
    'YYYY-MM-DDZ',
    'YYYY-MM-DDZZ',
    '-YYYY-MM-DD',
    '-YYYY-MM-DDZ',
    '-YYYY-MM-DDZZ',
];
